version: '3'
services:
  mongo:
    image: mongo:3.6.3-jessie
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - '27017:27017'
    volumes:
      - './volume:/data/db'
